<?xml version="1.0" ?>
<!DOCTYPE DefaultRegistrySettings [
  <!ELEMENT DefaultRegistrySettings ANY>
  <!ELEMENT DefaultSetting ANY>
  <!ATTLIST DefaultSetting id ID #REQUIRED>
  <!ELEMENT string ANY>
]>

<!--This file contains default registry settings -->

<DefaultRegistrySettings>
  <!-- Theme settings -->
  <DefaultSetting id="Skin">0</DefaultSetting>
  <DefaultSetting id="FrontEndTheme">Redmond</DefaultSetting>
  <DefaultSetting id="FrontEndReverseBackground">false</DefaultSetting>
  <DefaultSetting id="GlobalFontName">Calibri</DefaultSetting>
  <!-- Regional settings -->
  <DefaultSetting id="Language">en-US</DefaultSetting>
  <!-- Auto settings -->
  <DefaultSetting id="FormSize">800; 500</DefaultSetting>
  <DefaultSetting id="FormWindowState">0</DefaultSetting>
  <!-- Dev settings -->
  <DefaultSetting id="FrontEndBrowserDebugMode">false</DefaultSetting>
</DefaultRegistrySettings>